### ISSUE TITLE
[enhancement] Other middle-button shortcuts don't work

### ISSUE THREAD

**Issue by da411d** [AMPivovarov/FastMouseScroll#3] opened 2020-09-08 10:14 UTC
I often use middle-button to open links or includes.
For fast scrolling i use press-move-release, not press-move-press_again.

Can you add option to configure this behavour?

**Comment by da411d** [comment] 2020-09-09 17:59
@AMPivovarov ping

**Comment by AMPivovarov** [comment] 2020-11-09 11:26
Due to nature of how event handling in IDE works, it might be hard to implement.
Most shortcuts are handled on 'MOUSE_RELEASED', while drag-to-scroll should start on 'MOUSE_PRESSED'.

Which means we can't consume any 'MOUSE_PRESSED' events, as we don't know yet if it's press-move-release or click-move-click.
While it seems to work with "Go to declaration", I suspect something to break in this mode.

But you can try build from https://plugins.jetbrains.com/plugin/12388-fast-mouse-scrolling/versions/test channel.

**Comment by AMPivovarov** [comment] 2021-06-14 13:09
>I suspect something to break in this mode.

Bugs from a brief check on a Kotlin project:
* "Find Usages" popup is triggered, if drag-scroll starts on suitable element. (expected: only scroll happens)
* "Go to Declaration" action is triggered, if drag-scroll starts and ends on the suitable element (ex: class name), not necessary the same element. (expected: only scroll happens)

Probably, not worth merging uness these are fixed.

Interestingly, can reproduce on Windows - but not on Linux (after configuring middle-click for GotoDefinition action).

**Comment by da411d** [comment] 2021-06-14 13:24
In Google Chrome when dragging with middle button on link both are not triggering: no drag scroll and no open link in new tab👀

**Comment by AMPivovarov** [comment] 2021-06-14 21:46
>Bugs from a brief check on a Kotlin project:

Should be fixed in 1.5.8-a (https://plugins.jetbrains.com/plugin/12388-fast-mouse-scrolling/versions/test/122734).

**Comment by da411d** [comment] 2021-06-15 06:10
Yes, looks fine!

**Comment by da411d** [comment] 2021-06-15 06:14
I disabled "click-to-scroll" option and now when i click the variable or method - it shows its usages, as needed.
But when i press the mouse middle button, cursor changes to arrows for a while.
I suggest to change cursor after drag starts, at least for clickable objects

**Closed as completed** 2021-06-16 22:46 UTC
